In [74]:
from tensorflow.keras.preprocessing.text import one_hot

In [75]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [76]:

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [77]:
#define vocab size
voc_size = 10000

In [78]:
one_hot_repr= [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[948, 8095, 6215, 609],
 [948, 8095, 6215, 7252],
 [948, 7002, 6215, 9589],
 [7283, 6692, 4448, 2519, 8283],
 [7283, 6692, 4448, 2519, 1538],
 [7697, 948, 2527, 6215, 4569],
 [5236, 8556, 5426, 2519]]

### scale and normalize the array

In [79]:

max_value = max(max(sub_array) for sub_array in one_hot_repr)
scaled_array = [[round(element / max_value, 3) for element in sub_array] for sub_array in one_hot_repr]

print("Largest number in the array:", max_value)

for row in scaled_array:
    print(row)



Largest number in the array: 9589
[0.099, 0.844, 0.648, 0.064]
[0.099, 0.844, 0.648, 0.756]
[0.099, 0.73, 0.648, 1.0]
[0.76, 0.698, 0.464, 0.263, 0.864]
[0.76, 0.698, 0.464, 0.263, 0.16]
[0.803, 0.099, 0.264, 0.648, 0.476]
[0.546, 0.892, 0.566, 0.263]


In [95]:
## word embedding representation
import tensorflow
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [81]:
import numpy as np 

In [88]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='post',maxlen=sent_length)
embedded_docs

array([[ 948, 8095, 6215,  609,    0,    0,    0,    0],
       [ 948, 8095, 6215, 7252,    0,    0,    0,    0],
       [ 948, 7002, 6215, 9589,    0,    0,    0,    0],
       [7283, 6692, 4448, 2519, 8283,    0,    0,    0],
       [7283, 6692, 4448, 2519, 1538,    0,    0,    0],
       [7697,  948, 2527, 6215, 4569,    0,    0,    0],
       [5236, 8556, 5426, 2519,    0,    0,    0,    0]])

In [92]:
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim))
model.compile(optimizer='adam',loss='mse')

In [94]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [85]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step


array([[[-0.01212097,  0.03893511, -0.03505677, -0.02859261,
          0.04113424, -0.04164313,  0.03710182, -0.02294725,
          0.00981795, -0.02517819],
        [-0.01212097,  0.03893511, -0.03505677, -0.02859261,
          0.04113424, -0.04164313,  0.03710182, -0.02294725,
          0.00981795, -0.02517819],
        [-0.01212097,  0.03893511, -0.03505677, -0.02859261,
          0.04113424, -0.04164313,  0.03710182, -0.02294725,
          0.00981795, -0.02517819],
        [-0.01212097,  0.03893511, -0.03505677, -0.02859261,
          0.04113424, -0.04164313,  0.03710182, -0.02294725,
          0.00981795, -0.02517819],
        [-0.020332  , -0.04894588, -0.03297511, -0.00068703,
         -0.02912153,  0.00509931,  0.02475006, -0.01694978,
          0.00046831, -0.00154852],
        [-0.02675949,  0.0316251 , -0.04298922, -0.03091935,
          0.00364643, -0.00855187, -0.02316886,  0.04024483,
         -0.0197005 ,  0.03780414],
        [ 0.0294132 , -0.02530179,  0.04589787,  0.0

In [86]:
embedded_docs[0]

array([   0,    0,    0,    0,  948, 8095, 6215,  609])

In [87]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None